### ISSUE TITLE
reject ruleset for many Specified path on all domain

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman-rulesets#1]
this is more like captcha ruleset.
i need reject   ads  ad _stats   and more so i put them on top of persistent and temporary ruleset
and how add more path to them

**Comment by futpib** [comment]
@heforfree Check [this example](https://github.com/futpib/policeman-rulesets/blob/master/examples/reject_special_paths.ruleset). Does it answer your question?

**Comment by heforfree** [comment]
@futpib 
_stats working example on github i see it blocked xhrs request
but /ad not working, just in case i have to rename to ads and adv to test
in below site i want filter  ads,adv path but not working(ads are in the left of site)

i allow image from asriran.com to asriran.com and put myrulset on top but still i can see image

and seems such as rule slow down browser

**Comment by heforfree** [comment]
@futpib 
so why the second one not working?

**Comment by heforfree** [comment]
thank you i see you updated ruleset and now working
thanks,best regards

**Comment by heforfree** [comment]
@futpib 
i updated reject_special_paths.ruleset for myself with some more path.if you want update it on your
example
https://gist.github.com/heforfree/e9c4ecae8e3bf88217c0
