### ISSUE TITLE
Allow XHR same site

### ISSUE THREAD

**Issue by Firminator** [futpib/policeman-rulesets#14]
futpib,
what needs to be added if XHRs from same base domain should be allowed? In other words, what's the 'contentType' for XHRs?

For example if 'Pages' from same site should be allowed to load I would modify the existing ruleset ( https://github.com/futpib/policeman-rulesets/blob/master/general/allow_styles_and_images_and_fonts_same_site.ruleset ) and add 'PAGE' as contentType, but what about XHR? I tested and adding XHR doesn't work:

`[contentType] (STYLESHEET|IMAGE|FONT|PAGE|XHR<-doesn't work):`
`[schemeType] web -> web:`
`[baseDomain] * -> $&: ACCEPT`

**Comment by futpib** [comment]
It's `XMLHTTPREQUEST` ([src](https://github.com/futpib/policeman/blob/6f85ffa0d9eb67f397359f8a6fb68ad1955e72d7/src/lib/request-info.coffee#L169)).

**Comment by Firminator** [comment]
Thanks. I'll give this a try.

**Comment by Firminator** [comment]
That worked. Awesome. Thanks.
