### ISSUE TITLE
Do you plan to link to this repo from within the addon?

### ISSUE THREAD

**Issue by bastik-1001** [futpib/policeman-rulesets#4]
Is it planned to have a link like "Download rulsets" inside the addon?

Maybe it is OK to wait until [issue 114 of policeman](https://github.com/futpib/policeman/issues/114) is closed. (What's described there sounds really useful, especially if it is fine grained.)

**Comment by futpib** [comment]
Yes, but not anytime soon. Generally, I'd like rulesets to be updatable like adblock's subscriptions, when that is done, this repo may come handy. For now it's just a bunch of examples.
