### ISSUE TITLE
ruleset to pervent exe download? and hide placeholder for reject_special_paths.ruleset

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman-rulesets#5]
is this possible make an ruleset to pervent downloading exe file in firefox?
and i want hide placeholder for everything that match with this ruleset : reject_special_paths.ruleset
is this possible?
also can you extract Ghostery database?
thanks

**Comment by futpib** [comment]
##### exe

By filename only, sure. Just add something like `* ".exe": REJECT` to your _reject_special_paths.ruleset_

##### placeholder

futpib/policeman#153

##### Ghostery

Do they distribute it freely?

**Comment by heforfree** [comment]
i try below line and work very good
    -> \* ".exe": REJECT

this what i see inside an addon.
This proprietary database is protected by copyright, and is owned exclusively by Ghostery and all rights to it are expressly reserved.
     If you are interested in using this database for any purpose outside of the Ghostery application, contact Ghostery at info@ghostery.com.
