### ISSUE TITLE
ruleset for allow redirect for same site and second level domain

### ISSUE THREAD

**Issue by heforfree** [futpib/policeman-rulesets#6]
please make an ruleset for allow redirect for same site and second level domain

**Comment by futpib** [comment]
[allow_redirects_same_site.ruleset](https://github.com/futpib/policeman-rulesets/blob/master/general/allow_redirects_same_site.ruleset)

**Comment by heforfree** [comment]
also this ruleset dont allow S3.Google connect to google translate
check for update addon too not working
