### ISSUE TITLE
Is it possible to allow images and styles from [any site] to *cdn*.

### ISSUE THREAD

**Issue by skudo12** [futpib/policeman-rulesets#8]
Basically a ruleset to allow image and style request from [any site] to site with a "cdn" in the name.
Could also work to allow scripts request from [any site] to site with "api" in the name. 
EDIT: Also image and style request from [any site] to site with "static" in the name.
Thank you.

**Comment by futpib** [comment]
[This should do](https://github.com/futpib/policeman-rulesets/blob/master/examples/allow_hosts_that_look_like_cdns.ruleset) (didn't test it; report back if it fails)

**Comment by skudo12** [comment]
Tested and working fine. Thanks!
